# datafiles
# Copyright (c), 2020-2020, Huawei Tech. Co., Ltd.
# Author: Zhang Tianxing <zhangtianxing3@huawei.com>

name := datafiles

top_srcdir		?= ../../../..

include $(top_srcdir)/include/mk/env_pre.mk

INSTALL_DIR		:= testcases/data/ima_digest_lists

INSTALL_TARGETS         += tree-digest-list
INSTALL_TARGETS         += tree-digest-list.sig

include $(top_srcdir)/include/mk/generic_leaf_target.mk
