# appraise
 # Copyright (c), 2020-2020, Huawei Tech. Co., Ltd.
# Author: Zhang Tianxing <zhangtianxing3@huawei.com>

name := measure

top_srcdir              ?= ../../../..

include $(top_srcdir)/include/mk/testcases.mk

INSTALL_TARGETS         += test_tcb_policy.sh
INSTALL_TARGETS         += test_tcb_attr.sh
INSTALL_TARGETS         += test_tcb_access.sh
INSTALL_TARGETS         += test_tcb_digest.sh

include $(top_srcdir)/include/mk/generic_leaf_target.mk
